title:        Adopta Agency
url:          http://adopta.agency
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 25
paginate_path: "/blog/page:num"

production_url : http://adopta.agency

BASE_PATH : http://adopta.agency

categories_path : /categories.html
tags_path : /tags.html
